// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/services" | "/portfolio" | "/pricing" | "/signup" | "/onboarding" | "/dashboard" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/services.tsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/portfolio.tsx": {
    id: "routes/portfolio";
    page: "/portfolio";
  };
  "routes/pricing.tsx": {
    id: "routes/pricing";
    page: "/pricing";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/services": typeof import("./app/routes/services.tsx");
  "routes/portfolio": typeof import("./app/routes/portfolio.tsx");
  "routes/pricing": typeof import("./app/routes/pricing.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
};